import { Injectable, Logger } from '@nestjs/common';
import {
  AccountType,
  ApprovalStatus,
  GuarantorStatus,
  LoanStatus,
  Prisma,
  UserRole,
} from '@prisma/client';
import { Decimal } from 'decimal.js';
import { mkdir, writeFile } from 'fs/promises';
import { dirname, resolve } from 'path';
import { PrismaService } from '../prisma/prisma.service';

const DUAL_APPROVAL_THRESHOLD = 500_000;
const SYSTEM_REMEDIATION_ACTOR = 'SYSTEM_REMEDIATION';
const REMEDIATION_COMMENT =
  'Auto-generated by data remediation script to satisfy schema constraints for historical loans approved prior to dual-approval enforcement. Requires manual compliance sign-off.';

interface CommandOptions {
  dryRun: boolean;
  outputPath: string;
  syntheticChains: boolean;
}

interface RemediationStats {
  strandedFound: number;
  guarantorsReleased: number;
  missingAccounts: number;
  zeroFrozenAccounts: number;
  guarantorErrors: number;
  missingChainsFound: number;
  syntheticChainsCreated: number;
  chainErrors: number;
  outputPath: string;
}

type StrandedGuarantor = {
  id: string;
  tenantId: string;
  loanId: string;
  memberId: string;
  guaranteedAmount: Prisma.Decimal;
  loan: {
    loanNumber: string;
    status: LoanStatus;
    loanProduct: { requiredAccountType: AccountType | null } | null;
  };
};

type MissingChainLoan = {
  id: string;
  tenantId: string;
  memberId: string;
  loanNumber: string;
  status: LoanStatus;
  principalAmount: Prisma.Decimal;
  approvedAt: Date | null;
  approvedBy: string | null;
};

@Injectable()
export class RemediateStrandedDataCommand {
  private readonly logger = new Logger(RemediateStrandedDataCommand.name);

  constructor(private readonly prisma: PrismaService) {}

  async execute(args: string[] = []): Promise<RemediationStats> {
    const options = this.parseOptions(args);
    const stats: RemediationStats = {
      strandedFound: 0,
      guarantorsReleased: 0,
      missingAccounts: 0,
      zeroFrozenAccounts: 0,
      guarantorErrors: 0,
      missingChainsFound: 0,
      syntheticChainsCreated: 0,
      chainErrors: 0,
      outputPath: options.outputPath,
    };

    this.logger.log(`Starting stranded data remediation (${options.dryRun ? 'DRY RUN' : 'LIVE'})`);

    await this.releaseStrandedGuarantorFunds(options, stats);
    await this.remediateMissingApprovalChains(options, stats);

    this.logger.log(
      `Remediation complete: released=${stats.guarantorsReleased}, missingAccounts=${stats.missingAccounts}, ` +
        `missingChains=${stats.missingChainsFound}, syntheticChains=${stats.syntheticChainsCreated}, ` +
        `errors=${stats.guarantorErrors + stats.chainErrors}`,
    );

    return stats;
  }

  private parseOptions(args: string[]): CommandOptions {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const outputArg = args.find((arg) => arg.startsWith('--output='));

    return {
      dryRun: args.includes('--dry-run'),
      syntheticChains: !args.includes('--no-synthetic-chains'),
      outputPath: resolve(
        process.cwd(),
        outputArg?.slice('--output='.length) ?? `remediation-missing-4eyes-${timestamp}.json`,
      ),
    };
  }

  private async releaseStrandedGuarantorFunds(
    options: CommandOptions,
    stats: RemediationStats,
  ): Promise<void> {
    const candidates = await this.prisma.loanGuarantor.findMany({
      where: {
        status: GuarantorStatus.ACCEPTED,
        holdReleasedAt: null,
        loan: {
          status: { in: [LoanStatus.REJECTED, LoanStatus.REJECTED_GUARANTOR_DECLINE] },
        },
      },
      select: {
        id: true,
        tenantId: true,
        loanId: true,
        memberId: true,
        guaranteedAmount: true,
        loan: {
          select: {
            loanNumber: true,
            status: true,
            loanProduct: { select: { requiredAccountType: true } },
          },
        },
      },
      orderBy: { createdAt: 'asc' },
    });

    stats.strandedFound = candidates.length;
    this.logger.log(`Task A: found ${candidates.length} stranded guarantor hold(s)`);

    for (const guarantor of candidates) {
      try {
        if (options.dryRun) {
          this.logger.log(
            `[DRY RUN] Would release guarantor=${guarantor.id} loan=${guarantor.loan.loanNumber} ` +
              `amount=${guarantor.guaranteedAmount.toString()}`,
          );
          continue;
        }

        const result = await this.releaseOneGuarantorHold(guarantor);
        if (result.missingAccount) stats.missingAccounts++;
        if (result.zeroFrozen) stats.zeroFrozenAccounts++;
        stats.guarantorsReleased++;
      } catch (error) {
        stats.guarantorErrors++;
        this.logger.error(
          `Failed to remediate guarantor=${guarantor.id} loan=${guarantor.loanId}: ${
            error instanceof Error ? error.message : String(error)
          }`,
        );
      }
    }
  }

  private async releaseOneGuarantorHold(
    guarantor: StrandedGuarantor,
  ): Promise<{ missingAccount: boolean; zeroFrozen: boolean }> {
    const accountType = guarantor.loan.loanProduct?.requiredAccountType ?? AccountType.FOSA;
    const releasedAt = new Date();
    const txClient = this.prisma.direct ?? this.prisma;

    return txClient.$transaction(
      async (tx) => {
        const lockedGuarantors = await tx.$queryRaw<
          Array<{
            id: string;
            status: GuarantorStatus;
            holdReleasedAt: Date | null;
            guaranteedAmount: Prisma.Decimal;
          }>
        >`
          SELECT id, status, "holdReleasedAt", "guaranteedAmount"
          FROM "Guarantor"
          WHERE id = ${guarantor.id} AND "tenantId" = ${guarantor.tenantId}
          FOR UPDATE
        `;
        const lockedGuarantor = lockedGuarantors[0];
        if (
          !lockedGuarantor ||
          lockedGuarantor.status !== GuarantorStatus.ACCEPTED ||
          lockedGuarantor.holdReleasedAt
        ) {
          return { missingAccount: false, zeroFrozen: false };
        }

        const account = await tx.account.findFirst({
          where: {
            tenantId: guarantor.tenantId,
            memberId: guarantor.memberId,
            accountType,
          },
          select: { id: true },
          orderBy: [{ isActive: 'desc' }, { createdAt: 'asc' }],
        });

        if (!account) {
          await this.markGuarantorReleased(tx, guarantor, releasedAt, '0.0000', {
            reason: 'GUARANTOR_ACCOUNT_MISSING',
            accountType,
          });
          return { missingAccount: true, zeroFrozen: false };
        }

        const lockedAccounts = await tx.$queryRaw<
          Array<{ id: string; frozenSavings: Prisma.Decimal; version: number }>
        >`
          SELECT id, "frozenSavings", version
          FROM "Account"
          WHERE id = ${account.id}
          FOR UPDATE
        `;
        const lockedAccount = lockedAccounts[0];
        if (!lockedAccount) {
          await this.markGuarantorReleased(tx, guarantor, releasedAt, '0.0000', {
            reason: 'GUARANTOR_ACCOUNT_MISSING_AFTER_LOOKUP',
            accountType,
            accountId: account.id,
          });
          return { missingAccount: true, zeroFrozen: false };
        }

        const frozenSavings = new Decimal(lockedAccount.frozenSavings.toString());
        const guaranteedAmount = new Decimal(lockedGuarantor.guaranteedAmount.toString());
        const releaseAmount = Decimal.min(frozenSavings, guaranteedAmount).toDecimalPlaces(4);

        if (releaseAmount.greaterThan(0)) {
          const updated = await tx.account.updateMany({
            where: {
              id: lockedAccount.id,
              tenantId: guarantor.tenantId,
              version: lockedAccount.version,
              frozenSavings: { gte: releaseAmount.toString() },
            },
            data: {
              frozenSavings: { decrement: releaseAmount.toString() },
              version: { increment: 1 },
            },
          });

          if (updated.count !== 1) {
            throw new Error('Concurrent balance modification, retry');
          }
        }

        await this.markGuarantorReleased(tx, guarantor, releasedAt, releaseAmount.toString(), {
          accountId: lockedAccount.id,
          accountType,
          frozenSavingsBefore: frozenSavings.toFixed(4),
        });

        return { missingAccount: false, zeroFrozen: releaseAmount.isZero() };
      },
      { isolationLevel: 'Serializable' as const },
    );
  }

  private async markGuarantorReleased(
    tx: Prisma.TransactionClient,
    guarantor: StrandedGuarantor,
    releasedAt: Date,
    releaseAmount: string,
    extraMetadata: Record<string, unknown>,
  ): Promise<void> {
    await tx.loanGuarantor.update({
      where: { id: guarantor.id },
      data: {
        status: GuarantorStatus.RELEASED,
        holdReleasedAt: releasedAt,
        notes: 'Released by historical data remediation after rejected-loan status bypass.',
      },
    });

    await tx.auditLog.create({
      data: {
        tenantId: guarantor.tenantId,
        actorId: null,
        action: 'REMEDIATION.GUARANTOR_HOLD_RELEASED',
        entityType: 'LoanGuarantor',
        entityId: guarantor.id,
        requestId: `remediation:guarantor-release:${guarantor.id}`,
        metadata: {
          actor: SYSTEM_REMEDIATION_ACTOR,
          loanId: guarantor.loanId,
          loanNumber: guarantor.loan.loanNumber,
          loanStatus: guarantor.loan.status,
          guarantorMemberId: guarantor.memberId,
          guaranteedAmount: guarantor.guaranteedAmount.toString(),
          releasedAmount: releaseAmount,
          releasedAt: releasedAt.toISOString(),
          ...extraMetadata,
        },
      },
    });
  }

  private async remediateMissingApprovalChains(
    options: CommandOptions,
    stats: RemediationStats,
  ): Promise<void> {
    const loans = await this.prisma.loan.findMany({
      where: {
        principalAmount: { gte: new Prisma.Decimal(DUAL_APPROVAL_THRESHOLD) },
        status: { in: [LoanStatus.APPROVED, LoanStatus.DISBURSED, LoanStatus.ACTIVE] },
        approvalChains: { none: {} },
      },
      select: {
        id: true,
        tenantId: true,
        memberId: true,
        loanNumber: true,
        status: true,
        principalAmount: true,
        approvedAt: true,
        approvedBy: true,
      },
      orderBy: { approvedAt: 'asc' },
    });

    stats.missingChainsFound = loans.length;
    await this.writeMissingChainsReport(options.outputPath, loans);
    this.logger.log(`Task B: found ${loans.length} high-value loan(s) missing approval chains`);
    this.logger.log(`Task B report written to ${options.outputPath}`);

    if (!options.syntheticChains) {
      this.logger.warn('Synthetic chain creation disabled by --no-synthetic-chains');
      return;
    }

    for (const loan of loans) {
      try {
        if (options.dryRun) {
          this.logger.log(
            `[DRY RUN] Would create synthetic approval chain for loan=${loan.id} ` +
              `principal=${loan.principalAmount.toString()}`,
          );
          continue;
        }

        const created = await this.createSyntheticApprovalChain(loan);
        if (created) stats.syntheticChainsCreated++;
      } catch (error) {
        stats.chainErrors++;
        this.logger.error(
          `Failed to remediate approval chain for loan=${loan.id}: ${
            error instanceof Error ? error.message : String(error)
          }`,
        );
      }
    }
  }

  private async createSyntheticApprovalChain(loan: MissingChainLoan): Promise<boolean> {
    const txClient = this.prisma.direct ?? this.prisma;
    return txClient.$transaction(
      async (tx) => {
        const lockedLoans = await tx.$queryRaw<Array<{ id: string }>>`
          SELECT id
          FROM "Loan"
          WHERE id = ${loan.id} AND "tenantId" = ${loan.tenantId}
          FOR UPDATE
        `;
        if (!lockedLoans[0]) return false;

        const existing = await tx.loanApprovalChain.count({
          where: { tenantId: loan.tenantId, loanId: loan.id },
        });
        if (existing > 0) return false;

        const decidedAt = new Date();
        const chain = await tx.loanApprovalChain.create({
          data: {
            tenantId: loan.tenantId,
            loanId: loan.id,
            approverId: SYSTEM_REMEDIATION_ACTOR,
            role: UserRole.MANAGER,
            status: ApprovalStatus.APPROVED,
            notes: REMEDIATION_COMMENT,
            decidedAt,
          },
        });

        await tx.auditLog.create({
          data: {
            tenantId: loan.tenantId,
            actorId: null,
            action: 'REMEDIATION.LOAN_APPROVAL_CHAIN_SYNTHETIC',
            entityType: 'Loan',
            entityId: loan.id,
            requestId: `remediation:approval-chain:${loan.id}`,
            metadata: {
              actor: SYSTEM_REMEDIATION_ACTOR,
              chainId: chain.id,
              loanNumber: loan.loanNumber,
              principalAmount: loan.principalAmount.toString(),
              status: loan.status,
              approvedAt: loan.approvedAt?.toISOString() ?? null,
              approvedBy: loan.approvedBy,
              comment: REMEDIATION_COMMENT,
              requiresManualComplianceSignOff: true,
            },
          },
        });

        return true;
      },
      { isolationLevel: 'Serializable' as const },
    );
  }

  private async writeMissingChainsReport(
    outputPath: string,
    loans: MissingChainLoan[],
  ): Promise<void> {
    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(
      outputPath,
      `${JSON.stringify(
        {
          generatedAt: new Date().toISOString(),
          thresholdKes: DUAL_APPROVAL_THRESHOLD,
          count: loans.length,
          loans: loans.map((loan) => ({
            id: loan.id,
            tenantId: loan.tenantId,
            memberId: loan.memberId,
            loanNumber: loan.loanNumber,
            status: loan.status,
            principalAmount: loan.principalAmount.toString(),
            approvedAt: loan.approvedAt?.toISOString() ?? null,
            approvedBy: loan.approvedBy,
          })),
        },
        null,
        2,
      )}\n`,
      'utf8',
    );
  }
}
