/**
 * Canonical audit action strings – single source of truth.
 * Import from here instead of using string literals in services.
 */
export const AUDIT_ACTIONS = {
  AUTH: {
    LOGIN: 'AUTH.LOGIN',
    LOGIN_FAILED: 'AUTH.LOGIN.FAILED',
    LOGOUT: 'AUTH.LOGOUT',
    REGISTER: 'AUTH.REGISTER',
    TOKEN_REFRESH: 'AUTH.TOKEN.REFRESH',
    TOKEN_REUSE_DETECTED: 'AUTH.TOKEN.REUSE_DETECTED',
    FORGOT_PASSWORD_REQUESTED: 'AUTH.FORGOT_PASSWORD.REQUESTED',
    RESET_PASSWORD: 'AUTH.RESET_PASSWORD',
    RESET_PASSWORD_FAILED: 'AUTH.RESET_PASSWORD.FAILED',
    CHANGE_PASSWORD: 'AUTH.CHANGE_PASSWORD',
    CHANGE_PASSWORD_FAILED: 'AUTH.CHANGE_PASSWORD.FAILED',
    PASSWORD_RESET_SMS_REQUESTED: 'AUTH.PASSWORD_RESET_SMS.REQUESTED',
    PASSWORD_RESET_SMS_COMPLETED: 'AUTH.PASSWORD_RESET_SMS.COMPLETED',
    PASSWORD_RESET_SMS_FAILED: 'AUTH.PASSWORD_RESET_SMS.FAILED',
  },
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS] extends infer U
  ? U extends Record<string, string>
    ? U[keyof U]
    : never
  : never;
